package com.myweb.core.persistence.entity;

// default package
// Generated 25-Oct-2017 23:46:53 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EmployeeEntity generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "dutyrostering", uniqueConstraints = @UniqueConstraint(columnNames = "USERNAME"))
public class EmployeeEntity{

	private short empId;
	private String username;
	private String password;
	private String fullName;
	private Date createDate;
	private boolean isActive;
	private boolean isAdmin;
	private List<RosterEntity> rosterEntities;

	public EmployeeEntity() {
	}

	public EmployeeEntity(short empId, String username, String password, String fullName, Date createDate, boolean isActive,
			boolean isAdmin) {
		this.empId = empId;
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.createDate = createDate;
		this.isActive = isActive;
		this.isAdmin = isAdmin;
	}

	public EmployeeEntity(short empId, String username, String password, String fullName, Date createDate, boolean isActive,
			boolean isAdmin, List<RosterEntity> rosterEntities) {
		this.empId = empId;
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.createDate = createDate;
		this.isActive = isActive;
		this.isAdmin = isAdmin;
		this.rosterEntities = rosterEntities;
	}

	@Id

	@Column(name = "EMP_ID", unique = true, nullable = false)
	public short getEmpId() {
		return this.empId;
	}

	public void setEmpId(short empId) {
		this.empId = empId;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 32)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "FULL_NAME", nullable = false, length = 50)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "IS_ACTIVE", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "IS_ADMIN", nullable = false)
	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeEntity")
	public List<RosterEntity> getRosterEntities() {
		return this.rosterEntities;
	}

	public void setRosterEntities(List<RosterEntity> rosterEntities) {
		this.rosterEntities = rosterEntities;
	}

}
