package com.myweb.core.persistence.entity;

// default package
// Generated 25-Oct-2017 23:46:53 by Hibernate Tools 5.2.5.Final

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShiftTypeEntity generated by hbm2java
 */
@Entity
@Table(name = "shift_type", catalog = "dutyrostering")
public class ShiftTypeEntity{

	private short shiftTypeId;
	private String name;
	private List<RosterEntity> rosterEntities;

	public ShiftTypeEntity() {
	}

	public ShiftTypeEntity(short shiftTypeId, String name) {
		this.shiftTypeId = shiftTypeId;
		this.name = name;
	}

	public ShiftTypeEntity(short shiftTypeId, String name, List<RosterEntity> rosterEntities) {
		this.shiftTypeId = shiftTypeId;
		this.name = name;
		this.rosterEntities = rosterEntities;
	}

	@Id

	@Column(name = "SHIFT_TYPE_ID", unique = true, nullable = false)
	public short getShiftTypeId() {
		return this.shiftTypeId;
	}

	public void setShiftTypeId(short shiftTypeId) {
		this.shiftTypeId = shiftTypeId;
	}

	@Column(name = "NAME", nullable = false, length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shiftTypeEntity")
	public List<RosterEntity> getRosterEntities() {
		return this.rosterEntities;
	}

	public void setRosterEntities(List<RosterEntity> rosterEntities) {
		this.rosterEntities = rosterEntities;
	}

}
