package com.myweb.core.persistence.enity;

// default package
// Generated 25-Oct-2017 23:46:53 by Hibernate Tools 5.2.5.Final

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShiftType generated by hbm2java
 */
@Entity
@Table(name = "shift_type", catalog = "dutyrostering")
public class ShiftType{

	private short shiftTypeId;
	private String name;
	private List<Roster> rosters;

	public ShiftType() {
	}

	public ShiftType(short shiftTypeId, String name) {
		this.shiftTypeId = shiftTypeId;
		this.name = name;
	}

	public ShiftType(short shiftTypeId, String name, List<Roster> rosters) {
		this.shiftTypeId = shiftTypeId;
		this.name = name;
		this.rosters = rosters;
	}

	@Id

	@Column(name = "SHIFT_TYPE_ID", unique = true, nullable = false)
	public short getShiftTypeId() {
		return this.shiftTypeId;
	}

	public void setShiftTypeId(short shiftTypeId) {
		this.shiftTypeId = shiftTypeId;
	}

	@Column(name = "NAME", nullable = false, length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shiftType")
	public List<Roster> getRosters() {
		return this.rosters;
	}

	public void setRosters(List<Roster> rosters) {
		this.rosters = rosters;
	}

}
